"""Real-ocean wave model driven by NOAA NDBC buoy data.

Supports two input formats:
    * .txt   realtime2  --  hourly significant wave height + dominant period
    * .spec  realtime2 spectra -- separate swell and wind-wave components

The output is an Ocean-compatible object that the dynamics simulator and
the RL environment can consume unchanged.

Data sources used here:
    data/ndbc_46012_realtime.txt   -- Humboldt Bay, CA, USA (~1097 hourly rec.)
    data/ndbc_46026_spectral.txt   -- Cape San Martin, CA, USA
                                     (swell + wind wave decomposition)
"""
from __future__ import annotations

import math
import os
from pathlib import Path
from dataclasses import dataclass, field
import numpy as np

from ocean import Ocean, pm_spectrum, G


# ---------------------------------------------------------------------
def _parse_ndbc_realtime(path: str) -> dict:
    """Parse NOAA NDBC realtime2 .txt file into arrays of records."""
    Hs_list, Tp_list, year, month, day, hour = [], [], [], [], [], []
    with open(path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 10:
                continue
            try:
                Hs = float(parts[8])
                Td = float(parts[9])
            except ValueError:
                continue
            if not np.isfinite([Hs, Td]).all() or Hs <= 0 or Td <= 0:
                continue
            Hs_list.append(Hs)
            Tp_list.append(Td)
            year.append(int(parts[0])); month.append(int(parts[1]))
            day.append(int(parts[2]));   hour.append(int(parts[3]))
    return dict(
        Hs=np.array(Hs_list, dtype=np.float32),
        Tp=np.array(Tp_list, dtype=np.float32),
        year=np.array(year), month=np.array(month),
        day=np.array(day), hour=np.array(hour),
    )


def _parse_ndbc_spectral(path: str) -> dict:
    """Parse NOAA NDBC realtime2 spectral .spec file."""
    Hs_tot, Hs_swell_arr, T_swell_arr, Hs_wind_arr, T_wind_arr = [], [], [], [], []
    with open(path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 12:
                continue
            try:
                Hs      = float(parts[5])
                Hs_swl  = float(parts[6]); T_swl = float(parts[7])
                Hs_wnd  = float(parts[8]); T_wnd = float(parts[9])
            except ValueError:
                continue
            if (not np.isfinite([Hs, Hs_swl, T_swl, Hs_wnd, T_wnd]).all()
                    or Hs <= 0 or Hs_swl < 0 or Hs_wnd < 0
                    or (Hs_swl > 0 and T_swl <= 0)
                    or (Hs_wnd > 0 and T_wnd <= 0)):
                continue
            Hs_tot.append(Hs)
            Hs_swell_arr.append(Hs_swl if Hs_swl > 0 else 0.0)
            T_swell_arr.append(T_swl if T_swl > 0 else 1.0)
            Hs_wind_arr.append(Hs_wnd if Hs_wnd > 0 else 0.0)
            T_wind_arr.append(T_wnd if T_wnd > 0 else 1.0)
    return dict(
        Hs_total =np.array(Hs_tot,       dtype=np.float32),
        Hs_swell =np.array(Hs_swell_arr, dtype=np.float32),
        Tp_swell =np.array(T_swell_arr,  dtype=np.float32),
        Hs_wind  =np.array(Hs_wind_arr,  dtype=np.float32),
        Tp_wind  =np.array(T_wind_arr,   dtype=np.float32),
    )


# ---------------------------------------------------------------------
@dataclass
class RealOcean:
    """Composite ocean built from a swell + wind-wave component.

    The total significant wave height is
        Hs_total^2  =  Hs_swell^2 + Hs_wind^2
    Each component is independently generated by a Pierson-Moskowitz
    spectrum with its own peak period, then superposed in space-time.
    """

    Hs_swell: float = 1.5
    Tp_swell: float = 8.0
    Hs_wind:  float = 0.8
    Tp_wind:  float = 5.0
    n_freq:   int   = 48
    omega_lo: float = 0.2
    omega_hi: float = 4.0
    seed:     int   = 42
    label:    str   = ""

    omega_s: np.ndarray = field(init=False, repr=False)
    omega_w: np.ndarray = field(init=False, repr=False)
    amps_s:  np.ndarray = field(init=False, repr=False)
    amps_w:  np.ndarray = field(init=False, repr=False)
    phases_s: np.ndarray = field(init=False, repr=False)
    phases_w: np.ndarray = field(init=False, repr=False)
    k_s: np.ndarray = field(init=False, repr=False)
    k_w: np.ndarray = field(init=False, repr=False)

    def __post_init__(self):
        rng = np.random.default_rng(self.seed)
        # Swell component
        self.omega_s = np.linspace(self.omega_lo, self.omega_hi, self.n_freq)
        domega = self.omega_s[1] - self.omega_s[0]
        S_s = pm_spectrum(self.omega_s, self.Hs_swell, self.Tp_swell)
        self.amps_s = np.sqrt(2.0 * S_s * domega)
        self.phases_s = rng.uniform(0.0, 2.0 * math.pi, size=self.n_freq)
        self.k_s = self.omega_s ** 2 / G
        # Wind-wave component
        self.omega_w = np.linspace(self.omega_lo, self.omega_hi, self.n_freq)
        S_w = pm_spectrum(self.omega_w, self.Hs_wind, self.Tp_wind)
        self.amps_w = np.sqrt(2.0 * S_w * domega)
        self.phases_w = rng.uniform(0.0, 2.0 * math.pi, size=self.n_freq)
        self.k_w = self.omega_w ** 2 / G

    # ----- compatible with Ocean -----
    def eta(self, x, t):
        x = np.atleast_1d(x); t_arr = np.atleast_1d(t)
        arg_s = (self.k_s[:, None] * x[None, :]
                 - self.omega_s[:, None] * t + self.phases_s[:, None])
        arg_w = (self.k_w[:, None] * x[None, :]
                 - self.omega_w[:, None] * t + self.phases_w[:, None])
        return (self.amps_s[:, None] * np.cos(arg_s)
              + self.amps_w[:, None] * np.cos(arg_w)).sum(axis=0)

    def eta_field(self, x, t):
        X, T = np.meshgrid(x, t, indexing="xy")
        arg_s = (self.k_s[:, None, None] * X[None, :, :]
                 - self.omega_s[:, None, None] * T[None, :, :]
                 + self.phases_s[:, None, None])
        arg_w = (self.k_w[:, None, None] * X[None, :, :]
                 - self.omega_w[:, None, None] * T[None, :, :]
                 + self.phases_w[:, None, None])
        return (self.amps_s[:, None, None] * np.cos(arg_s)
              + self.amps_w[:, None, None] * np.cos(arg_w)).sum(axis=0)

    def elevation_at(self, x0, t):
        arg_s = (self.k_s[:, None] * x0
                 - np.outer(self.omega_s, t) + self.phases_s[:, None])
        arg_w = (self.k_w[:, None] * x0
                 - np.outer(self.omega_w, t) + self.phases_w[:, None])
        return ((self.amps_s[:, None] * np.cos(arg_s)).sum(axis=0)
              + (self.amps_w[:, None] * np.cos(arg_w)).sum(axis=0))

    def statistics(self, x0: float = 0.0, t: np.ndarray | None = None,
                   n_samples: int = 20000) -> dict:
        if t is None:
            t = np.linspace(0.0, 600.0, n_samples)
        eta = self.elevation_at(x0, t)
        eta_dot = np.gradient(eta, t)
        m0 = float(np.mean(eta ** 2))
        m2 = float(np.mean(eta_dot ** 2))
        # Composite Hs: Hs_total^2 = Hs_swell^2 + Hs_wind^2
        Hs_comp = math.sqrt(self.Hs_swell**2 + self.Hs_wind**2)
        return {
            "Hs_target":    Hs_comp,
            "Hs_observed":  4.0 * math.sqrt(m0),
            "Hs_swell":     self.Hs_swell,
            "Hs_wind":      self.Hs_wind,
            "Tp_swell":     self.Tp_swell,
            "Tp_wind":      self.Tp_wind,
            "eta_rms":      math.sqrt(m0),
            "crest_max":    float(eta.max()),
            "trough_min":   float(eta.min()),
            "Hmax_est":     float(eta.max() - eta.min()),
        }


# ---------------------------------------------------------------------
def load_buoy_default(realtime_path=None, spectral_path=None):
    """Build a RealOcean from the latest measurements of the two files.

    The 'latest' record is the first non-header data line in the NDBC file
    (NDBC writes most-recent at the top of realtime files).
    """
    root = Path(__file__).resolve().parent / "data"
    realtime_path = root / "ndbc_46012_realtime.txt" if realtime_path is None else Path(realtime_path)
    spectral_path = root / "ndbc_46026_spectral.txt" if spectral_path is None else Path(spectral_path)
    sp = _parse_ndbc_spectral(spectral_path) if spectral_path.exists() else None
    if sp is not None and len(sp["Hs_total"]):
        # latest is index 0 (NDBC writes newest at top)
        Hs_sw = float(sp["Hs_swell"][0])
        T_sw  = float(sp["Tp_swell"][0])
        Hs_ww = float(sp["Hs_wind"][0])
        T_ww  = float(sp["Tp_wind"][0])
        return RealOcean(Hs_swell=Hs_sw, Tp_swell=T_sw,
                         Hs_wind=Hs_ww, Tp_wind=T_ww,
                         label=f"NDBC 46026 (latest, swell+wind)")
    if realtime_path.exists():
        rt = _parse_ndbc_realtime(realtime_path)
        if not len(rt["Hs"]):
            raise ValueError("NDBC files contain no valid wave records")
        Hs = float(rt["Hs"][0]); Td = float(rt["Tp"][0])
        # Use full Hs as the swell component (dominant) and 30 % of that as
        # a smaller wind-wave component for texture.
        return RealOcean(Hs_swell=Hs * math.sqrt(1 - 0.3**2), Tp_swell=Td,
                         Hs_wind=0.3 * Hs, Tp_wind=max(3.0, 0.6 * Td),
                         label=f"NDBC 46012 (latest Hs={Hs:.1f} m, Tp={Td:.1f} s)")
    raise FileNotFoundError("no NDBC data file found")


# ---------------------------------------------------------------------
if __name__ == "__main__":
    sea = load_buoy_default()
    print(f"Real-ocean composite:  {sea.label}")
    print(f"  Hs_swell = {sea.Hs_swell:.2f} m,  Tp_swell = {sea.Tp_swell:.2f} s")
    print(f"  Hs_wind  = {sea.Hs_wind:.2f} m,  Tp_wind  = {sea.Tp_wind:.2f} s")
    stats = sea.statistics()
    for k, v in stats.items():
        print(f"  {k:12s}: {v:.3f}")
    # Show sample of realtime file
    rt = _parse_ndbc_realtime("data/ndbc_46012_realtime.txt")
    print(f"\nNDBC 46012 records: {len(rt['Hs'])} hourly samples")
    print(f"  Hs range  : {rt['Hs'].min():.2f} .. {rt['Hs'].max():.2f} m")
    print(f"  Tp range  : {rt['Tp'].min():.2f} .. {rt['Tp'].max():.2f} s")
    print(f"  Hs mean   : {rt['Hs'].mean():.2f} m")
    print(f"  Tp mean   : {rt['Tp'].mean():.2f} s")