"""Open-sea irregular wave model.

Uses the Pierson-Moskowitz (PM) spectrum for a fully developed sea,
generated by random superposition of linear sinusoidal components.
An optional JONSWAP peak enhancement (gamma > 1) models fetch-limited
seas; gamma = 1 reproduces the PM spectrum exactly.

Linear wave theory (Airy) is assumed:
    eta(x, t) = sum_i a_i * cos(k_i * x  -  omega_i * t  +  phi_i)

with deep-water dispersion  omega^2 = g k  and amplitudes drawn so that
2 S(omega_i) domega = a_i^2.  With ``finite_depth=True`` the full
relation  omega^2 = g k tanh(k h)  is solved for k instead.

The model provides:
    * one spatial series eta(x)         (used for geometry visualisation)
    * one spatio-temporal field eta(x, t)  (used by the dynamics sim)
    * statistics  (Hs, Tp, Hmax_est)
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
import numpy as np

G = 9.80665


# ---------------------------------------------------------------------
#  Spectrum
# ---------------------------------------------------------------------
def pm_spectrum(omega: np.ndarray, Hs: float, Tp: float) -> np.ndarray:
    """Pierson-Moskowitz spectral density S(omega).

    omega : rad/s
    Hs   : significant wave height, m
    Tp   : peak spectral period, s

    Returns
    -------
    S : spectral density (m^2 / (rad/s))

    Normalisation is chosen so that  m0 = integral(S d omega) = Hs^2 / 16
    (which is the definition of significant wave height for narrow-band sea).
    """
    if not np.isfinite(Hs) or Hs < 0 or not np.isfinite(Tp) or Tp <= 0:
        raise ValueError("Hs must be nonnegative and Tp positive (both finite)")
    omega_p = 2 * math.pi / Tp
    S = ((5.0 / 16.0) * (Hs ** 2) * (omega_p ** 4)
         / (omega ** 5)
         * np.exp(- (5.0 / 4.0) * (omega_p / omega) ** 4))
    return S


def jonswap_spectrum(omega: np.ndarray, Hs: float, Tp: float,
                     gamma: float = 1.0) -> np.ndarray:
    """JONSWAP spectral density: PM shape with a peak-enhancement factor.

    S(omega) = A_gamma * S_PM(omega) * gamma ** r(omega)
    r(omega) = exp(-(omega - omega_p)^2 / (2 sigma^2 omega_p^2))
    sigma    = 0.07 (omega <= omega_p) or 0.09 (omega > omega_p)
    A_gamma  = 1 - 0.287 ln(gamma)   (keeps m0 ~ Hs^2/16)

    gamma = 1 returns the PM spectrum bit-for-bit.
    Typical North-Sea range is gamma in [1, 7] (mean ~3.3).
    """
    if not np.isfinite(gamma) or gamma < 1.0:
        raise ValueError("gamma must be finite and >= 1")
    S = pm_spectrum(omega, Hs, Tp)
    if gamma == 1.0:
        return S
    omega_p = 2 * math.pi / Tp
    omega = np.asarray(omega, dtype=float)
    sigma = np.where(omega <= omega_p, 0.07, 0.09)
    r = np.exp(-(omega - omega_p) ** 2 / (2.0 * sigma ** 2 * omega_p ** 2))
    A_gamma = 1.0 - 0.287 * math.log(gamma)
    return S * A_gamma * gamma ** r


def dispersion_k(omega: np.ndarray, depth: float | None = None) -> np.ndarray:
    """Wave number from the linear dispersion relation.

    depth None or inf  ->  deep-water limit  k = omega^2 / g.
    Otherwise solves   omega^2 = g k tanh(k depth)   by Newton iteration
    starting from the Eckart approximation (exact in both the deep- and
    shallow-water limits, so convergence is a few iterations).
    """
    omega = np.asarray(omega, dtype=float)
    if depth is None or math.isinf(depth):
        return omega ** 2 / G
    if not np.isfinite(depth) or depth <= 0:
        raise ValueError("depth must be positive and finite")
    arg = omega ** 2 * depth / G
    k = omega ** 2 / (G * np.sqrt(np.tanh(np.maximum(arg, 1e-12))))
    for _ in range(50):
        th = np.tanh(k * depth)
        f = G * k * th - omega ** 2
        df = G * th + G * k * depth * (1.0 - th ** 2)
        dk = f / np.maximum(df, 1e-12)
        k = np.maximum(k - dk, 1e-9)
        if np.all(np.abs(dk) <= 1e-13 * k):
            break
    return k


@dataclass
class Ocean:
    Hs:    float = 1.5      # significant wave height, m
    Tp:    float = 6.0      # peak spectral period, s
    depth: float = 50.0     # water depth, m  (deep-water limit)
    n_freq: int = 64        # number of spectral components
    omega_lo: float = 0.2   # low-frequency cut-off, rad/s
    omega_hi: float = 4.0   # high-frequency cut-off, rad/s
    seed: int = 42          # RNG seed for repeatability
    gamma: float = 1.0      # JONSWAP peak enhancement (1 = PM exactly)
    finite_depth: bool = False  # solve omega^2 = g k tanh(k*depth) for k
    omega: np.ndarray = field(init=False, repr=False)
    domega: float = field(init=False, repr=False)
    amps: np.ndarray = field(init=False, repr=False)
    phases: np.ndarray = field(init=False, repr=False)
    k: np.ndarray = field(init=False, repr=False)

    def __post_init__(self):
        if (self.n_freq < 2 or not np.isfinite([self.omega_lo, self.omega_hi]).all()
                or not 0 < self.omega_lo < self.omega_hi):
            raise ValueError("invalid frequency grid")
        rng = np.random.default_rng(self.seed)
        # Equi-spaced frequency grid (used as quadrature)
        self.omega = np.linspace(self.omega_lo, self.omega_hi, self.n_freq)
        self.domega = self.omega[1] - self.omega[0]
        S = jonswap_spectrum(self.omega, self.Hs, self.Tp, self.gamma)
        # Component amplitudes
        self.amps = np.sqrt(2.0 * S * self.domega)
        # Uniform random phases
        self.phases = rng.uniform(0.0, 2.0 * math.pi, size=self.n_freq)
        # Wave numbers: deep water unless finite-depth dispersion requested
        self.k = dispersion_k(self.omega,
                              self.depth if self.finite_depth else None)

    # -- Queries ------------------------------------------------------
    def eta(self, x: float | np.ndarray, t: float) -> float | np.ndarray:
        """Surface elevation at (x, t)."""
        arg = (np.multiply.outer(self.k, np.atleast_1d(x))
               - np.outer(self.omega, np.full_like(np.atleast_1d(x), t))
               + self.phases[:, None])
        return (self.amps[:, None] * np.cos(arg)).sum(axis=0)

    def eta_field(self, x: np.ndarray, t: np.ndarray) -> np.ndarray:
        """Full spatio-temporal field. x:(Nx,), t:(Nt,) -> eta:(Nt, Nx)."""
        X, T = np.meshgrid(x, t, indexing="xy")    # (Nt, Nx)
        # Broadcast frequency axis into a 3-D array (n_freq, Nt, Nx)
        k = self.k[:, None, None]
        w = self.omega[:, None, None]
        ph = self.phases[:, None, None]
        arg = k * X[None, :, :] - w * T[None, :, :] + ph
        return (self.amps[:, None, None] * np.cos(arg)).sum(axis=0)

    def elevation_at(self, x0: float, t: np.ndarray) -> np.ndarray:
        """Time history at fixed x0."""
        return (self.amps[:, None] * np.cos(
                   self.k[:, None] * x0
                   - np.outer(self.omega, t)
                   + self.phases[:, None])).sum(axis=0)

    # -- Statistics ---------------------------------------------------
    def statistics(self, x0: float = 0.0, t: np.ndarray | None = None,
                   n_samples: int = 20000) -> dict:
        """Monte-Carlo sea-state statistics."""
        if t is None:
            t = np.linspace(0.0, 600.0, n_samples)
        eta = self.elevation_at(x0, t)
        eta_dot = np.gradient(eta, t)
        m0 = np.mean(eta ** 2)
        m2 = np.mean(eta_dot ** 2)
        Hs_calc = 4.0 * math.sqrt(m0)
        Tz_calc = 2 * math.pi * math.sqrt(m0 / m2) if m2 > 0 else float("nan")
        crest_max = eta.max()
        trough_min = eta.min()
        return {
            "Hs_target":       self.Hs,
            "Hs_observed":      Hs_calc,
            "Tp_target":       self.Tp,
            "Tz_observed":     Tz_calc,
            "eta_rms":         math.sqrt(m0),
            "crest_max":       float(crest_max),
            "trough_min":      float(trough_min),
            "Hmax_est":        float(crest_max - trough_min),
        }


# ---------------------------------------------------------------------
if __name__ == "__main__":
    sea = Ocean(Hs=1.5, Tp=6.0, seed=42)
    print("PM spectrum discrete components n =", sea.n_freq)
    print("omega range =", sea.omega[0], "..", sea.omega[-1], "rad/s")
    stats = sea.statistics()
    for k, v in stats.items():
        print(f"  {k:15s}: {v:.3f}")
    # Sample elevation profile
    x = np.linspace(0, 80, 401)
    eta0 = sea.eta(x, 0.0)
    print(f"\nSpatial snapshot: rms={np.sqrt(np.mean(eta0**2)):.3f} m, "
          f"max={eta0.max():.3f}, min={eta0.min():.3f}")